import type {
  AgentCognitiveData,
  AgentCognitiveProfile,
  SkillChain,
  ToolPolicy,
  DelegationPolicy,
  RuntimeProfile,
  AuditDriftReport,
  MemorySource,
  CognitiveHealth,
  DashboardMetrics,
} from "@paperclipai/shared";

// ---------------------------------------------------------------------------
// Agent IDs (stable across mock data so other files can cross-reference)
// ---------------------------------------------------------------------------

const AGENT_IDS = {
  ceo: "agent-ceo-001",
  cto: "agent-cto-002",
  engineer: "agent-eng-003",
  designer: "agent-des-004",
  pm: "agent-pm-005",
  qa: "agent-qa-006",
} as const;

// ---------------------------------------------------------------------------
// Helper: deterministic ISO timestamps relative to "now"
// ---------------------------------------------------------------------------

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

// ---------------------------------------------------------------------------
// CEO / Founder
// ---------------------------------------------------------------------------

const ceoProfile: AgentCognitiveProfile = {
  mission:
    "Define product vision, allocate resources, and ensure company-wide alignment toward quarterly OKRs.",
  cognitiveRole: "Strategic Orchestrator",
  specialization: "High-level decision making and delegation",
  priorityStack: [
    "Evaluate strategic alignment of all proposals",
    "Delegate execution to domain leads",
    "Approve or reject budget-impacting decisions",
    "Monitor company-wide health metrics",
  ],
  decisionRules: [
    "Never commit to technical implementation details directly",
    "Escalate financial decisions above $10k to human board",
    "Require CTO sign-off on any architecture change",
  ],
  reasoningSequence: [
    "Assess strategic impact",
    "Check resource availability",
    "Evaluate risk profile",
    "Delegate to appropriate lead",
    "Set review checkpoint",
  ],
  escalationTriggers: [
    "Budget request exceeds quarterly allocation",
    "Cross-team conflict unresolved after 2 cycles",
    "Customer-facing incident severity >= P1",
  ],
  antiPatterns: [
    "Micro-managing implementation details",
    "Bypassing CTO on technical decisions",
    "Making promises without resource check",
  ],
  boundaryRules: [
    "Do not write code or review PRs",
    "Do not directly assign tasks to ICs",
    "Always route through team leads",
  ],
  confidencePolicy: "high",
  edgeCaseRules: [
    "If all leads are blocked, escalate to human operator",
    "If conflicting OKRs detected, pause and request alignment meeting",
  ],
  capabilityTags: ["Strategy", "Governance", "Routing"],
  healthStatus: "healthy",
  driftStatus: 0.02,
  blueprintVersion: "2.1.0",
  lastSyncAt: daysAgo(1),
  modelTier: "frontier",
  toolCount: 4,
};

const ceoSkillChains: SkillChain[] = [
  {
    id: "sc-ceo-001",
    agentId: AGENT_IDS.ceo,
    name: "Strategic Planning Cycle",
    description: "Quarterly OKR setting and resource allocation workflow",
    isPrimary: true,
    startConditions: ["Quarter start", "Major pivot request"],
    steps: [
      {
        id: "scs-ceo-001-1",
        chainId: "sc-ceo-001",
        orderIndex: 0,
        type: "action",
        title: "Gather team status reports",
        description: "Request status from all department leads",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "All leads have reported within 24h",
        failureCondition: "Missing reports after 48h",
      },
      {
        id: "scs-ceo-001-2",
        chainId: "sc-ceo-001",
        orderIndex: 1,
        type: "decision",
        title: "Evaluate priorities",
        description: "Rank initiatives by strategic value and feasibility",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Priority stack established",
        failureCondition: "Conflicting priorities unresolvable",
      },
      {
        id: "scs-ceo-001-3",
        chainId: "sc-ceo-001",
        orderIndex: 2,
        type: "delegation",
        title: "Assign OKRs to leads",
        description: "Delegate specific OKRs to CTO, PM, and Designer",
        toolRequired: null,
        delegateTarget: "agent-cto-002,agent-pm-005,agent-des-004",
        escalationTarget: null,
        successCondition: "All OKRs accepted by leads",
        failureCondition: "Lead rejects OKR as infeasible",
      },
      {
        id: "scs-ceo-001-4",
        chainId: "sc-ceo-001",
        orderIndex: 3,
        type: "review",
        title: "Mid-cycle checkpoint",
        description: "Review progress against OKRs at cycle midpoint",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: "human-operator",
        successCondition: "All OKRs on track or adjusted",
        failureCondition: "Critical OKR behind with no recovery plan",
      },
    ],
    branches: {
      "lead-rejects-okr": "sc-ceo-002",
    },
    completionCriteria: "All OKRs assigned and acknowledged",
    fallbackBehavior: "Escalate to human operator for manual priority setting",
    version: "1.3.0",
  },
];

const ceoToolPolicies: ToolPolicy[] = [
  {
    id: "tp-ceo-001",
    agentId: AGENT_IDS.ceo,
    toolName: "company_dashboard",
    permissionLevel: "full",
    usageConditions: ["Monitoring company health", "Preparing status reports"],
    doNotUseConditions: [],
    fallbackBehavior: "Request manual report from PM",
    preconditions: [],
    notes: "Primary monitoring tool",
    lastUpdated: daysAgo(7),
    successRate: 0.98,
    failureRate: 0.02,
    usageCount: 342,
  },
  {
    id: "tp-ceo-002",
    agentId: AGENT_IDS.ceo,
    toolName: "budget_allocator",
    permissionLevel: "restricted",
    usageConditions: ["Quarterly planning", "Emergency reallocation"],
    doNotUseConditions: ["Routine expenses under $500"],
    fallbackBehavior: "Submit budget request through approval flow",
    preconditions: ["Must have quarterly plan approved"],
    notes: "Restricted to prevent over-allocation",
    lastUpdated: daysAgo(14),
    successRate: 0.95,
    failureRate: 0.05,
    usageCount: 28,
  },
  {
    id: "tp-ceo-003",
    agentId: AGENT_IDS.ceo,
    toolName: "agent_messenger",
    permissionLevel: "full",
    usageConditions: ["Delegation", "Status requests", "Escalation routing"],
    doNotUseConditions: [],
    fallbackBehavior: "Use shared context board",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(2),
    successRate: 0.99,
    failureRate: 0.01,
    usageCount: 891,
  },
  {
    id: "tp-ceo-004",
    agentId: AGENT_IDS.ceo,
    toolName: "code_editor",
    permissionLevel: "none",
    usageConditions: [],
    doNotUseConditions: ["Always - CEO should never write code"],
    fallbackBehavior: "Delegate to CTO or Engineer",
    preconditions: [],
    notes: "Boundary rule: CEO does not write code",
    lastUpdated: daysAgo(30),
    successRate: 0,
    failureRate: 0,
    usageCount: 0,
  },
];

const ceoDelegationPolicies: DelegationPolicy[] = [
  {
    id: "dp-ceo-001",
    agentId: AGENT_IDS.ceo,
    taskClass: "technical_architecture",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.cto,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "CTO owns all technical architecture decisions",
  },
  {
    id: "dp-ceo-002",
    agentId: AGENT_IDS.ceo,
    taskClass: "feature_prioritization",
    ownershipMode: "owns",
    delegateTo: null,
    escalateTo: "human-operator",
    approvalRequired: true,
    confidenceThreshold: "medium",
    notes: "CEO retains final say on feature priority",
  },
  {
    id: "dp-ceo-003",
    agentId: AGENT_IDS.ceo,
    taskClass: "design_review",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.designer,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "Designer owns design reviews",
  },
  {
    id: "dp-ceo-004",
    agentId: AGENT_IDS.ceo,
    taskClass: "project_coordination",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.pm,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "PM handles day-to-day coordination",
  },
];

const ceoRuntime: RuntimeProfile = {
  id: "rp-ceo-001",
  agentId: AGENT_IDS.ceo,
  adapter: "claude_local",
  modelName: "claude-opus-4-6",
  modelTier: "frontier",
  heartbeatMode: "on_demand",
  heartbeatInterval: 3600,
  cronJobs: ["daily-status-digest"],
  sandboxMode: false,
  accessProfile: "executive",
  environmentStatus: "active",
  exporterVersion: "1.2.0",
};

const ceoDrift: AuditDriftReport = {
  id: "adr-ceo-001",
  agentId: AGENT_IDS.ceo,
  blueprintVersion: "2.1.0",
  liveVersion: "2.1.0",
  driftScore: 0.02,
  missingFields: [],
  mismatchedFields: [],
  staleFields: [],
  lastAuditedAt: daysAgo(1),
  stewardRecommendations: [],
};

const ceoMemory: MemorySource[] = [
  {
    id: "ms-ceo-001",
    agentId: AGENT_IDS.ceo,
    name: "Company OKR Board",
    type: "shared_context",
    path: "/shared/okrs/current",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(0),
    freshnessScore: 0.99,
    dependencies: [],
  },
  {
    id: "ms-ceo-002",
    agentId: AGENT_IDS.ceo,
    name: "Strategy Documents",
    type: "file",
    path: "/docs/strategy/",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(3),
    freshnessScore: 0.92,
    dependencies: [],
  },
];

const ceoHealth: CognitiveHealth = {
  agentId: AGENT_IDS.ceo,
  alignmentScore: 0.97,
  driftScore: 0.02,
  completenessScore: 0.95,
  toolPolicyCoverage: 1.0,
  delegationCoverage: 0.92,
  lastAssessed: daysAgo(1),
};

// ---------------------------------------------------------------------------
// CTO
// ---------------------------------------------------------------------------

const ctoProfile: AgentCognitiveProfile = {
  mission:
    "Ensure technical excellence, review architecture decisions, and maintain code quality standards across all engineering output.",
  cognitiveRole: "Technical Authority",
  specialization: "Architecture review and technical strategy",
  priorityStack: [
    "Review and approve architecture proposals",
    "Ensure code quality standards are met",
    "Manage technical debt backlog",
    "Mentor engineering agents on best practices",
  ],
  decisionRules: [
    "Reject PRs with critical security vulnerabilities",
    "Require tests for any new feature code",
    "Approve architecture changes only after threat modeling",
  ],
  reasoningSequence: [
    "Analyze technical requirements",
    "Evaluate architecture impact",
    "Review security implications",
    "Assess performance characteristics",
    "Approve or request changes",
  ],
  escalationTriggers: [
    "Security vulnerability with CVSS >= 7.0",
    "Architecture change affecting more than 3 services",
    "Production outage lasting longer than 15 minutes",
  ],
  antiPatterns: [
    "Approving PRs without reading the diff",
    "Over-engineering simple features",
    "Ignoring tech debt for more than 2 sprints",
  ],
  boundaryRules: [
    "Do not override designer decisions on UX",
    "Do not assign business priorities - defer to CEO",
    "Always consult QA before releasing hotfixes",
  ],
  confidencePolicy: "high",
  edgeCaseRules: [
    "If unsure about security impact, block the PR and consult external security review",
    "For novel architecture patterns, prototype before committing",
  ],
  capabilityTags: ["Critique", "Analysis", "Strategy", "Governance"],
  healthStatus: "warning",
  driftStatus: 0.15,
  blueprintVersion: "2.0.3",
  lastSyncAt: daysAgo(3),
  modelTier: "frontier",
  toolCount: 8,
};

const ctoSkillChains: SkillChain[] = [
  {
    id: "sc-cto-001",
    agentId: AGENT_IDS.cto,
    name: "Code Review Pipeline",
    description:
      "Automated code review with security scanning and architecture validation",
    isPrimary: true,
    startConditions: ["PR opened", "Review requested"],
    steps: [
      {
        id: "scs-cto-001-1",
        chainId: "sc-cto-001",
        orderIndex: 0,
        type: "tool_call",
        title: "Run static analysis",
        description: "Execute linting and static security scans on the diff",
        toolRequired: "code_analyzer",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "No critical findings",
        failureCondition: "Critical or high severity finding detected",
      },
      {
        id: "scs-cto-001-2",
        chainId: "sc-cto-001",
        orderIndex: 1,
        type: "review",
        title: "Architecture review",
        description: "Evaluate changes against architecture guidelines",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Changes conform to architecture standards",
        failureCondition: "Architecture deviation detected",
      },
      {
        id: "scs-cto-001-3",
        chainId: "sc-cto-001",
        orderIndex: 2,
        type: "decision",
        title: "Approve or request changes",
        description: "Final decision on the PR based on all review data",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: AGENT_IDS.ceo,
        successCondition: "PR approved or changes requested with clear guidance",
        failureCondition: "Unable to determine impact",
      },
    ],
    branches: {
      "critical-security-finding": "sc-cto-003",
    },
    completionCriteria: "PR has a definitive approve or reject decision",
    fallbackBehavior: "Request human review with detailed findings",
    version: "2.1.0",
  },
  {
    id: "sc-cto-002",
    agentId: AGENT_IDS.cto,
    name: "Incident Response",
    description: "Production incident triage and resolution coordination",
    isPrimary: false,
    startConditions: ["P1 or P2 alert fired", "Manual escalation from engineer"],
    steps: [
      {
        id: "scs-cto-002-1",
        chainId: "sc-cto-002",
        orderIndex: 0,
        type: "tool_call",
        title: "Check monitoring dashboards",
        description: "Pull current system health metrics",
        toolRequired: "monitoring_dashboard",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Root cause hypothesis formed",
        failureCondition: "Insufficient data to diagnose",
      },
      {
        id: "scs-cto-002-2",
        chainId: "sc-cto-002",
        orderIndex: 1,
        type: "delegation",
        title: "Assign fix to engineer",
        description: "Delegate implementation of fix to available engineer",
        toolRequired: null,
        delegateTarget: AGENT_IDS.engineer,
        escalationTarget: null,
        successCondition: "Engineer acknowledges and begins fix",
        failureCondition: "No engineer available",
      },
      {
        id: "scs-cto-002-3",
        chainId: "sc-cto-002",
        orderIndex: 2,
        type: "review",
        title: "Verify fix",
        description: "Review and validate the deployed fix",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Metrics return to normal",
        failureCondition: "Issue persists after fix deployed",
      },
    ],
    branches: {},
    completionCriteria: "Incident resolved and post-mortem scheduled",
    fallbackBehavior: "Escalate to CEO for external support engagement",
    version: "1.0.0",
  },
];

const ctoToolPolicies: ToolPolicy[] = [
  {
    id: "tp-cto-001",
    agentId: AGENT_IDS.cto,
    toolName: "code_analyzer",
    permissionLevel: "full",
    usageConditions: ["PR review", "Security audit", "Tech debt assessment"],
    doNotUseConditions: [],
    fallbackBehavior: "Manual code review",
    preconditions: ["Code must be committed to a branch"],
    notes: "Primary review tool",
    lastUpdated: daysAgo(5),
    successRate: 0.96,
    failureRate: 0.04,
    usageCount: 1247,
  },
  {
    id: "tp-cto-002",
    agentId: AGENT_IDS.cto,
    toolName: "monitoring_dashboard",
    permissionLevel: "full",
    usageConditions: ["Incident response", "Performance review"],
    doNotUseConditions: [],
    fallbackBehavior: "Request logs from DevOps",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(2),
    successRate: 0.99,
    failureRate: 0.01,
    usageCount: 456,
  },
  {
    id: "tp-cto-003",
    agentId: AGENT_IDS.cto,
    toolName: "code_editor",
    permissionLevel: "restricted",
    usageConditions: ["Hotfix only", "Prototype exploration"],
    doNotUseConditions: ["Feature development - delegate to engineer"],
    fallbackBehavior: "Delegate to engineer agent",
    preconditions: ["Must be a P1 incident or approved prototype"],
    notes: "CTO should primarily review, not write production code",
    lastUpdated: daysAgo(10),
    successRate: 0.92,
    failureRate: 0.08,
    usageCount: 34,
  },
  {
    id: "tp-cto-004",
    agentId: AGENT_IDS.cto,
    toolName: "dependency_scanner",
    permissionLevel: "full",
    usageConditions: ["Weekly dependency audit", "Pre-release check"],
    doNotUseConditions: [],
    fallbackBehavior: "Manual dependency review",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(7),
    successRate: 0.94,
    failureRate: 0.06,
    usageCount: 89,
  },
  {
    id: "tp-cto-005",
    agentId: AGENT_IDS.cto,
    toolName: "architecture_diagrammer",
    permissionLevel: "full",
    usageConditions: ["Architecture proposals", "System documentation"],
    doNotUseConditions: [],
    fallbackBehavior: "Text-based architecture description",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(21),
    successRate: 0.88,
    failureRate: 0.12,
    usageCount: 23,
  },
];

const ctoDelegationPolicies: DelegationPolicy[] = [
  {
    id: "dp-cto-001",
    agentId: AGENT_IDS.cto,
    taskClass: "feature_implementation",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.engineer,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "Engineers own implementation",
  },
  {
    id: "dp-cto-002",
    agentId: AGENT_IDS.cto,
    taskClass: "architecture_decision",
    ownershipMode: "owns",
    delegateTo: null,
    escalateTo: AGENT_IDS.ceo,
    approvalRequired: true,
    confidenceThreshold: "high",
    notes: "CTO makes final architecture calls",
  },
  {
    id: "dp-cto-003",
    agentId: AGENT_IDS.cto,
    taskClass: "testing",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.qa,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "medium",
    notes: "QA owns test coverage and validation",
  },
];

const ctoRuntime: RuntimeProfile = {
  id: "rp-cto-001",
  agentId: AGENT_IDS.cto,
  adapter: "claude_local",
  modelName: "claude-opus-4-6",
  modelTier: "frontier",
  heartbeatMode: "timer",
  heartbeatInterval: 1800,
  cronJobs: ["pr-review-queue", "weekly-dependency-scan", "daily-metrics-check"],
  sandboxMode: false,
  accessProfile: "engineering_lead",
  environmentStatus: "active",
  exporterVersion: "1.2.0",
};

const ctoDrift: AuditDriftReport = {
  id: "adr-cto-001",
  agentId: AGENT_IDS.cto,
  blueprintVersion: "2.0.3",
  liveVersion: "2.0.1",
  driftScore: 0.15,
  missingFields: ["edgeCaseRules[2]"],
  mismatchedFields: ["heartbeatInterval"],
  staleFields: ["architecture_diagrammer.lastUpdated"],
  lastAuditedAt: daysAgo(3),
  stewardRecommendations: [
    "Re-sync blueprint to pick up new edge case rules",
    "Update heartbeat interval from 1200 to 1800 in blueprint",
  ],
};

const ctoMemory: MemorySource[] = [
  {
    id: "ms-cto-001",
    agentId: AGENT_IDS.cto,
    name: "Architecture Decision Records",
    type: "file",
    path: "/docs/adr/",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(1),
    freshnessScore: 0.95,
    dependencies: [],
  },
  {
    id: "ms-cto-002",
    agentId: AGENT_IDS.cto,
    name: "Code Quality Metrics",
    type: "api",
    path: "/api/metrics/code-quality",
    readPermission: true,
    writePermission: false,
    lastRefresh: daysAgo(0),
    freshnessScore: 0.98,
    dependencies: ["monitoring_dashboard"],
  },
  {
    id: "ms-cto-003",
    agentId: AGENT_IDS.cto,
    name: "Tech Debt Registry",
    type: "database",
    path: "tech_debt_items",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(2),
    freshnessScore: 0.88,
    dependencies: [],
  },
];

const ctoHealth: CognitiveHealth = {
  agentId: AGENT_IDS.cto,
  alignmentScore: 0.89,
  driftScore: 0.15,
  completenessScore: 0.91,
  toolPolicyCoverage: 0.88,
  delegationCoverage: 0.85,
  lastAssessed: daysAgo(1),
};

// ---------------------------------------------------------------------------
// Engineer
// ---------------------------------------------------------------------------

const engineerProfile: AgentCognitiveProfile = {
  mission:
    "Implement features, fix bugs, and ship production-quality code following established architecture patterns and coding standards.",
  cognitiveRole: "Execution Specialist",
  specialization: "Full-stack implementation and debugging",
  priorityStack: [
    "Complete assigned implementation tasks",
    "Fix critical bugs in production",
    "Write tests for all new code",
    "Refactor code flagged as tech debt",
  ],
  decisionRules: [
    "Follow the architecture patterns documented in ADRs",
    "Ask CTO before introducing a new dependency",
    "Write unit tests before marking a task as done",
  ],
  reasoningSequence: [
    "Understand the requirements",
    "Check existing code for patterns",
    "Implement the solution",
    "Write tests",
    "Submit for review",
  ],
  escalationTriggers: [
    "Blocked by unclear requirements for more than 2 hours",
    "Bug in a system the engineer does not own",
    "Performance regression detected in CI",
  ],
  antiPatterns: [
    "Shipping code without tests",
    "Introducing new architectural patterns without CTO review",
    "Working on unassigned tasks without PM approval",
  ],
  boundaryRules: [
    "Do not deploy to production without QA sign-off",
    "Do not modify infrastructure config without DevOps review",
    "Do not change API contracts without PM notification",
  ],
  confidencePolicy: "medium",
  edgeCaseRules: [
    "If a task touches auth code, request additional security review from CTO",
    "If modifying shared types, coordinate with all downstream consumers",
  ],
  capabilityTags: ["Execution", "Analysis"],
  healthStatus: "healthy",
  driftStatus: 0.05,
  blueprintVersion: "1.8.2",
  lastSyncAt: daysAgo(0),
  modelTier: "standard",
  toolCount: 12,
};

const engineerSkillChains: SkillChain[] = [
  {
    id: "sc-eng-001",
    agentId: AGENT_IDS.engineer,
    name: "Feature Implementation",
    description:
      "End-to-end feature development from spec to merged PR",
    isPrimary: true,
    startConditions: ["Issue assigned", "Task moved to in_progress"],
    steps: [
      {
        id: "scs-eng-001-1",
        chainId: "sc-eng-001",
        orderIndex: 0,
        type: "action",
        title: "Read and analyze requirements",
        description: "Parse the issue description and acceptance criteria",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: AGENT_IDS.pm,
        successCondition: "Clear understanding of what to build",
        failureCondition: "Ambiguous or conflicting requirements",
      },
      {
        id: "scs-eng-001-2",
        chainId: "sc-eng-001",
        orderIndex: 1,
        type: "tool_call",
        title: "Explore existing codebase",
        description: "Search for related code, patterns, and shared utilities",
        toolRequired: "code_search",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Found relevant code patterns to follow",
        failureCondition: "No existing patterns found",
      },
      {
        id: "scs-eng-001-3",
        chainId: "sc-eng-001",
        orderIndex: 2,
        type: "tool_call",
        title: "Implement solution",
        description: "Write the code following established patterns",
        toolRequired: "code_editor",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Code compiles and passes local checks",
        failureCondition: "Compilation errors or type mismatches",
      },
      {
        id: "scs-eng-001-4",
        chainId: "sc-eng-001",
        orderIndex: 3,
        type: "tool_call",
        title: "Write tests",
        description: "Create unit and integration tests for the new code",
        toolRequired: "test_runner",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "All tests pass with adequate coverage",
        failureCondition: "Tests fail or coverage below threshold",
      },
      {
        id: "scs-eng-001-5",
        chainId: "sc-eng-001",
        orderIndex: 4,
        type: "tool_call",
        title: "Submit PR",
        description: "Create pull request with description and link to issue",
        toolRequired: "git_cli",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "PR created and CI passes",
        failureCondition: "CI pipeline fails",
      },
    ],
    branches: {
      "unclear-requirements": "sc-eng-003",
    },
    completionCriteria: "PR merged and issue closed",
    fallbackBehavior: "Escalate to CTO with detailed blocker report",
    version: "3.0.1",
  },
];

const engineerToolPolicies: ToolPolicy[] = [
  {
    id: "tp-eng-001",
    agentId: AGENT_IDS.engineer,
    toolName: "code_editor",
    permissionLevel: "full",
    usageConditions: ["Any assigned implementation task"],
    doNotUseConditions: [],
    fallbackBehavior: "N/A - primary tool",
    preconditions: ["Must have an assigned task"],
    notes: "Primary tool for implementation",
    lastUpdated: daysAgo(0),
    successRate: 0.94,
    failureRate: 0.06,
    usageCount: 4521,
  },
  {
    id: "tp-eng-002",
    agentId: AGENT_IDS.engineer,
    toolName: "test_runner",
    permissionLevel: "full",
    usageConditions: ["After writing code", "Before submitting PR"],
    doNotUseConditions: [],
    fallbackBehavior: "Run tests manually via CLI",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(0),
    successRate: 0.91,
    failureRate: 0.09,
    usageCount: 3876,
  },
  {
    id: "tp-eng-003",
    agentId: AGENT_IDS.engineer,
    toolName: "git_cli",
    permissionLevel: "full",
    usageConditions: ["Branching", "Committing", "PR creation"],
    doNotUseConditions: ["Force push to main"],
    fallbackBehavior: "Request manual git operations",
    preconditions: [],
    notes: "Never force push to main or production branches",
    lastUpdated: daysAgo(1),
    successRate: 0.97,
    failureRate: 0.03,
    usageCount: 2134,
  },
  {
    id: "tp-eng-004",
    agentId: AGENT_IDS.engineer,
    toolName: "code_search",
    permissionLevel: "full",
    usageConditions: ["Exploring codebase", "Finding patterns"],
    doNotUseConditions: [],
    fallbackBehavior: "Manual file browsing",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(0),
    successRate: 0.93,
    failureRate: 0.07,
    usageCount: 1893,
  },
  {
    id: "tp-eng-005",
    agentId: AGENT_IDS.engineer,
    toolName: "debugger",
    permissionLevel: "full",
    usageConditions: ["Bug investigation", "Performance profiling"],
    doNotUseConditions: [],
    fallbackBehavior: "Console logging",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(3),
    successRate: 0.87,
    failureRate: 0.13,
    usageCount: 567,
  },
  {
    id: "tp-eng-006",
    agentId: AGENT_IDS.engineer,
    toolName: "database_client",
    permissionLevel: "read_only",
    usageConditions: ["Debugging data issues", "Verifying migrations"],
    doNotUseConditions: ["Production data modification"],
    fallbackBehavior: "Request database changes through migration scripts",
    preconditions: ["Must be on staging or development environment"],
    notes: "Read-only access prevents accidental data mutation",
    lastUpdated: daysAgo(5),
    successRate: 0.96,
    failureRate: 0.04,
    usageCount: 234,
  },
];

const engineerDelegationPolicies: DelegationPolicy[] = [
  {
    id: "dp-eng-001",
    agentId: AGENT_IDS.engineer,
    taskClass: "testing_validation",
    ownershipMode: "collaborates",
    delegateTo: AGENT_IDS.qa,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "medium",
    notes: "Engineer writes unit tests, QA handles integration and e2e",
  },
  {
    id: "dp-eng-002",
    agentId: AGENT_IDS.engineer,
    taskClass: "architecture_decision",
    ownershipMode: "escalates",
    delegateTo: null,
    escalateTo: AGENT_IDS.cto,
    approvalRequired: true,
    confidenceThreshold: "escalate",
    notes: "All architecture decisions go to CTO",
  },
];

const engineerRuntime: RuntimeProfile = {
  id: "rp-eng-001",
  agentId: AGENT_IDS.engineer,
  adapter: "claude_local",
  modelName: "claude-sonnet-4-5-20250929",
  modelTier: "standard",
  heartbeatMode: "timer",
  heartbeatInterval: 300,
  cronJobs: ["ci-check", "pr-update-check"],
  sandboxMode: true,
  accessProfile: "developer",
  environmentStatus: "active",
  exporterVersion: "1.2.0",
};

const engineerDrift: AuditDriftReport = {
  id: "adr-eng-001",
  agentId: AGENT_IDS.engineer,
  blueprintVersion: "1.8.2",
  liveVersion: "1.8.2",
  driftScore: 0.05,
  missingFields: [],
  mismatchedFields: ["sandboxMode"],
  staleFields: [],
  lastAuditedAt: daysAgo(0),
  stewardRecommendations: [
    "Verify sandboxMode setting matches blueprint (expected true)",
  ],
};

const engineerMemory: MemorySource[] = [
  {
    id: "ms-eng-001",
    agentId: AGENT_IDS.engineer,
    name: "Codebase Index",
    type: "file",
    path: "/src/",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(0),
    freshnessScore: 1.0,
    dependencies: [],
  },
  {
    id: "ms-eng-002",
    agentId: AGENT_IDS.engineer,
    name: "CI Pipeline Results",
    type: "api",
    path: "/api/ci/results",
    readPermission: true,
    writePermission: false,
    lastRefresh: daysAgo(0),
    freshnessScore: 0.99,
    dependencies: ["test_runner"],
  },
];

const engineerHealth: CognitiveHealth = {
  agentId: AGENT_IDS.engineer,
  alignmentScore: 0.94,
  driftScore: 0.05,
  completenessScore: 0.96,
  toolPolicyCoverage: 0.92,
  delegationCoverage: 0.88,
  lastAssessed: daysAgo(0),
};

// ---------------------------------------------------------------------------
// Designer
// ---------------------------------------------------------------------------

const designerProfile: AgentCognitiveProfile = {
  mission:
    "Create intuitive, accessible, and visually cohesive user experiences through research-driven design and iterative prototyping.",
  cognitiveRole: "Creative Researcher",
  specialization: "UX/UI design and user research",
  priorityStack: [
    "Conduct user research for new features",
    "Create wireframes and prototypes",
    "Maintain design system consistency",
    "Review implemented UI against design specs",
  ],
  decisionRules: [
    "Always validate designs with accessibility checker",
    "Prefer existing design system components over custom solutions",
    "Require user research data before major UX changes",
  ],
  reasoningSequence: [
    "Research user needs",
    "Explore design patterns",
    "Create low-fidelity wireframes",
    "Iterate to high-fidelity prototypes",
    "Hand off to engineering with specs",
  ],
  escalationTriggers: [
    "Design system change affecting more than 5 components",
    "Accessibility audit failure",
    "Conflicting stakeholder feedback on design direction",
  ],
  antiPatterns: [
    "Designing without user research data",
    "Breaking design system consistency for one-off requests",
    "Skipping accessibility validation",
  ],
  boundaryRules: [
    "Do not implement designs in code directly",
    "Do not override CEO product decisions without discussion",
    "Always document design rationale",
  ],
  confidencePolicy: "medium",
  edgeCaseRules: [
    "For complex data visualization, consult with engineer on technical feasibility",
    "If design system component does not exist, propose a new one to CTO first",
  ],
  capabilityTags: ["Research", "Writing", "Analysis"],
  healthStatus: "drifted",
  driftStatus: 0.34,
  blueprintVersion: "1.5.0",
  lastSyncAt: daysAgo(12),
  modelTier: "standard",
  toolCount: 6,
};

const designerSkillChains: SkillChain[] = [
  {
    id: "sc-des-001",
    agentId: AGENT_IDS.designer,
    name: "Design Sprint",
    description: "End-to-end design process from research to handoff",
    isPrimary: true,
    startConditions: ["Feature request with UX impact", "Design task assigned"],
    steps: [
      {
        id: "scs-des-001-1",
        chainId: "sc-des-001",
        orderIndex: 0,
        type: "action",
        title: "User research",
        description: "Gather user insights and pain points for the feature",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Research findings documented",
        failureCondition: "Insufficient user data available",
      },
      {
        id: "scs-des-001-2",
        chainId: "sc-des-001",
        orderIndex: 1,
        type: "tool_call",
        title: "Create wireframes",
        description: "Build low-fidelity wireframes exploring solutions",
        toolRequired: "design_tool",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "At least 2 design options created",
        failureCondition: "Design tool unavailable",
      },
      {
        id: "scs-des-001-3",
        chainId: "sc-des-001",
        orderIndex: 2,
        type: "tool_call",
        title: "Accessibility check",
        description: "Validate designs meet WCAG 2.1 AA standards",
        toolRequired: "accessibility_checker",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "No critical accessibility issues",
        failureCondition: "Critical accessibility violations found",
      },
      {
        id: "scs-des-001-4",
        chainId: "sc-des-001",
        orderIndex: 3,
        type: "delegation",
        title: "Hand off to engineering",
        description: "Provide design specs and assets to engineer",
        toolRequired: null,
        delegateTarget: AGENT_IDS.engineer,
        escalationTarget: null,
        successCondition: "Engineer acknowledges design handoff",
        failureCondition: "Engineer flags feasibility concerns",
      },
    ],
    branches: {
      "feasibility-concern": "sc-des-002",
    },
    completionCriteria: "Design handed off and accepted by engineering",
    fallbackBehavior: "Schedule sync with CTO and engineer to resolve feasibility",
    version: "1.2.0",
  },
];

const designerToolPolicies: ToolPolicy[] = [
  {
    id: "tp-des-001",
    agentId: AGENT_IDS.designer,
    toolName: "design_tool",
    permissionLevel: "full",
    usageConditions: ["Wireframing", "Prototyping", "Design system updates"],
    doNotUseConditions: [],
    fallbackBehavior: "Text-based design description",
    preconditions: [],
    notes: "Primary design creation tool",
    lastUpdated: daysAgo(1),
    successRate: 0.95,
    failureRate: 0.05,
    usageCount: 1567,
  },
  {
    id: "tp-des-002",
    agentId: AGENT_IDS.designer,
    toolName: "accessibility_checker",
    permissionLevel: "full",
    usageConditions: ["All design reviews", "Pre-handoff validation"],
    doNotUseConditions: [],
    fallbackBehavior: "Manual accessibility checklist review",
    preconditions: ["Design must be in high-fidelity state"],
    notes: "Required before every engineering handoff",
    lastUpdated: daysAgo(8),
    successRate: 0.91,
    failureRate: 0.09,
    usageCount: 423,
  },
  {
    id: "tp-des-003",
    agentId: AGENT_IDS.designer,
    toolName: "user_research_db",
    permissionLevel: "full",
    usageConditions: ["Research phase", "Validating assumptions"],
    doNotUseConditions: [],
    fallbackBehavior: "Request research data from PM",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(15),
    successRate: 0.82,
    failureRate: 0.18,
    usageCount: 198,
  },
  {
    id: "tp-des-004",
    agentId: AGENT_IDS.designer,
    toolName: "component_library",
    permissionLevel: "read_only",
    usageConditions: ["Checking existing components", "Design system reference"],
    doNotUseConditions: ["Modifying components without CTO approval"],
    fallbackBehavior: "Browse design system docs",
    preconditions: [],
    notes: "Read-only to prevent unauthorized design system changes",
    lastUpdated: daysAgo(20),
    successRate: 0.97,
    failureRate: 0.03,
    usageCount: 892,
  },
];

const designerDelegationPolicies: DelegationPolicy[] = [
  {
    id: "dp-des-001",
    agentId: AGENT_IDS.designer,
    taskClass: "implementation",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.engineer,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "Designer hands off specs, engineer implements",
  },
  {
    id: "dp-des-002",
    agentId: AGENT_IDS.designer,
    taskClass: "design_system_update",
    ownershipMode: "collaborates",
    delegateTo: null,
    escalateTo: AGENT_IDS.cto,
    approvalRequired: true,
    confidenceThreshold: "needs_review",
    notes: "Design system changes need CTO review for tech impact",
  },
];

const designerRuntime: RuntimeProfile = {
  id: "rp-des-001",
  agentId: AGENT_IDS.designer,
  adapter: "claude_local",
  modelName: "claude-sonnet-4-5-20250929",
  modelTier: "standard",
  heartbeatMode: "on_demand",
  heartbeatInterval: 7200,
  cronJobs: ["design-system-audit"],
  sandboxMode: false,
  accessProfile: "creative",
  environmentStatus: "active",
  exporterVersion: "1.1.0",
};

const designerDrift: AuditDriftReport = {
  id: "adr-des-001",
  agentId: AGENT_IDS.designer,
  blueprintVersion: "1.5.0",
  liveVersion: "1.3.2",
  driftScore: 0.34,
  missingFields: ["edgeCaseRules", "boundaryRules[2]"],
  mismatchedFields: ["confidencePolicy", "heartbeatInterval", "modelTier"],
  staleFields: ["user_research_db.lastUpdated", "component_library.lastUpdated"],
  lastAuditedAt: daysAgo(12),
  stewardRecommendations: [
    "Blueprint is 2 versions behind - urgent re-sync required",
    "Confidence policy changed from 'high' to 'medium' without steward approval",
    "Tool policies for user_research_db and component_library are stale",
    "Run full cognitive audit to reconcile drifted fields",
  ],
};

const designerMemory: MemorySource[] = [
  {
    id: "ms-des-001",
    agentId: AGENT_IDS.designer,
    name: "Design System",
    type: "file",
    path: "/design/system/",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(2),
    freshnessScore: 0.85,
    dependencies: [],
  },
  {
    id: "ms-des-002",
    agentId: AGENT_IDS.designer,
    name: "User Research Archive",
    type: "database",
    path: "user_research_entries",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(5),
    freshnessScore: 0.72,
    dependencies: ["user_research_db"],
  },
];

const designerHealth: CognitiveHealth = {
  agentId: AGENT_IDS.designer,
  alignmentScore: 0.72,
  driftScore: 0.34,
  completenessScore: 0.78,
  toolPolicyCoverage: 0.80,
  delegationCoverage: 0.75,
  lastAssessed: daysAgo(5),
};

// ---------------------------------------------------------------------------
// PM (Project Manager)
// ---------------------------------------------------------------------------

const pmProfile: AgentCognitiveProfile = {
  mission:
    "Coordinate cross-team work, maintain project timelines, triage incoming requests, and ensure smooth information flow between all agents.",
  cognitiveRole: "Coordination Hub",
  specialization: "Task routing, scheduling, and stakeholder communication",
  priorityStack: [
    "Triage and route incoming tasks to correct agent",
    "Maintain project boards and timelines",
    "Facilitate cross-agent communication",
    "Report progress to CEO",
  ],
  decisionRules: [
    "Route technical tasks to CTO or Engineer based on complexity",
    "Escalate blockers within 1 cycle if no resolution",
    "Never modify code or design assets directly",
  ],
  reasoningSequence: [
    "Classify the incoming request",
    "Identify the right agent for the task",
    "Check agent availability and workload",
    "Route or queue the task",
    "Set follow-up checkpoint",
  ],
  escalationTriggers: [
    "Task blocked for more than 1 business day",
    "Multiple agents reporting conflicting priorities",
    "Customer-facing deadline at risk",
  ],
  antiPatterns: [
    "Making technical decisions instead of routing them",
    "Allowing task queue to grow unchecked",
    "Failing to communicate status updates to stakeholders",
  ],
  boundaryRules: [
    "Do not write code or create designs",
    "Do not approve architecture changes",
    "Always keep CEO informed of critical path changes",
  ],
  confidencePolicy: "high",
  edgeCaseRules: [
    "If task classification is ambiguous, ask the requester for clarification",
    "If all agents are at capacity, escalate to CEO for priority arbitration",
  ],
  capabilityTags: ["Routing", "Writing", "Analysis"],
  healthStatus: "healthy",
  driftStatus: 0.08,
  blueprintVersion: "1.6.1",
  lastSyncAt: daysAgo(2),
  modelTier: "fast",
  toolCount: 5,
};

const pmSkillChains: SkillChain[] = [
  {
    id: "sc-pm-001",
    agentId: AGENT_IDS.pm,
    name: "Task Triage and Routing",
    description: "Classify, prioritize, and route incoming tasks to the right agent",
    isPrimary: true,
    startConditions: ["New task created", "Task re-assigned", "Escalation received"],
    steps: [
      {
        id: "scs-pm-001-1",
        chainId: "sc-pm-001",
        orderIndex: 0,
        type: "action",
        title: "Classify task",
        description:
          "Determine task type (bug, feature, design, infra) and priority",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Task classified with type and priority",
        failureCondition: "Cannot determine task type from description",
      },
      {
        id: "scs-pm-001-2",
        chainId: "sc-pm-001",
        orderIndex: 1,
        type: "tool_call",
        title: "Check agent workload",
        description: "Review current workload of potential assignees",
        toolRequired: "workload_tracker",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Available agent identified",
        failureCondition: "All agents at capacity",
      },
      {
        id: "scs-pm-001-3",
        chainId: "sc-pm-001",
        orderIndex: 2,
        type: "delegation",
        title: "Assign task",
        description: "Route the task to the best-fit agent",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: AGENT_IDS.ceo,
        successCondition: "Agent acknowledges assignment",
        failureCondition: "Agent rejects or is unavailable",
      },
      {
        id: "scs-pm-001-4",
        chainId: "sc-pm-001",
        orderIndex: 3,
        type: "action",
        title: "Set checkpoint",
        description: "Schedule follow-up to check task progress",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Checkpoint scheduled",
        failureCondition: "N/A",
      },
    ],
    branches: {
      "all-agents-busy": "sc-pm-002",
    },
    completionCriteria: "Task assigned and checkpoint set",
    fallbackBehavior: "Queue the task and notify CEO of capacity issue",
    version: "2.0.0",
  },
];

const pmToolPolicies: ToolPolicy[] = [
  {
    id: "tp-pm-001",
    agentId: AGENT_IDS.pm,
    toolName: "project_board",
    permissionLevel: "full",
    usageConditions: ["Task management", "Status tracking", "Sprint planning"],
    doNotUseConditions: [],
    fallbackBehavior: "Maintain status in shared context",
    preconditions: [],
    notes: "Primary coordination tool",
    lastUpdated: daysAgo(0),
    successRate: 0.97,
    failureRate: 0.03,
    usageCount: 2891,
  },
  {
    id: "tp-pm-002",
    agentId: AGENT_IDS.pm,
    toolName: "workload_tracker",
    permissionLevel: "full",
    usageConditions: ["Task assignment", "Capacity planning"],
    doNotUseConditions: [],
    fallbackBehavior: "Ask agents directly for availability",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(1),
    successRate: 0.93,
    failureRate: 0.07,
    usageCount: 1456,
  },
  {
    id: "tp-pm-003",
    agentId: AGENT_IDS.pm,
    toolName: "agent_messenger",
    permissionLevel: "full",
    usageConditions: ["Notifications", "Status updates", "Coordination"],
    doNotUseConditions: [],
    fallbackBehavior: "Use shared context board",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(0),
    successRate: 0.99,
    failureRate: 0.01,
    usageCount: 3421,
  },
  {
    id: "tp-pm-004",
    agentId: AGENT_IDS.pm,
    toolName: "report_generator",
    permissionLevel: "full",
    usageConditions: ["Weekly reports", "Sprint retrospectives"],
    doNotUseConditions: [],
    fallbackBehavior: "Manual report writing",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(7),
    successRate: 0.90,
    failureRate: 0.10,
    usageCount: 67,
  },
  {
    id: "tp-pm-005",
    agentId: AGENT_IDS.pm,
    toolName: "code_editor",
    permissionLevel: "none",
    usageConditions: [],
    doNotUseConditions: ["Always - PM should never write code"],
    fallbackBehavior: "Delegate to Engineer",
    preconditions: [],
    notes: "Boundary rule: PM does not modify code",
    lastUpdated: daysAgo(30),
    successRate: 0,
    failureRate: 0,
    usageCount: 0,
  },
];

const pmDelegationPolicies: DelegationPolicy[] = [
  {
    id: "dp-pm-001",
    agentId: AGENT_IDS.pm,
    taskClass: "bug_fix",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.engineer,
    escalateTo: AGENT_IDS.cto,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "Bugs go to engineer, critical bugs also notify CTO",
  },
  {
    id: "dp-pm-002",
    agentId: AGENT_IDS.pm,
    taskClass: "design_request",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.designer,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "Design work routes to designer",
  },
  {
    id: "dp-pm-003",
    agentId: AGENT_IDS.pm,
    taskClass: "strategic_decision",
    ownershipMode: "escalates",
    delegateTo: null,
    escalateTo: AGENT_IDS.ceo,
    approvalRequired: true,
    confidenceThreshold: "escalate",
    notes: "PM does not make strategic decisions",
  },
  {
    id: "dp-pm-004",
    agentId: AGENT_IDS.pm,
    taskClass: "qa_validation",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.qa,
    escalateTo: null,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "Testing routes to QA",
  },
];

const pmRuntime: RuntimeProfile = {
  id: "rp-pm-001",
  agentId: AGENT_IDS.pm,
  adapter: "claude_local",
  modelName: "claude-haiku-4-5-20251001",
  modelTier: "fast",
  heartbeatMode: "timer",
  heartbeatInterval: 600,
  cronJobs: ["daily-standup-digest", "sprint-progress-check"],
  sandboxMode: false,
  accessProfile: "coordinator",
  environmentStatus: "active",
  exporterVersion: "1.2.0",
};

const pmDrift: AuditDriftReport = {
  id: "adr-pm-001",
  agentId: AGENT_IDS.pm,
  blueprintVersion: "1.6.1",
  liveVersion: "1.6.0",
  driftScore: 0.08,
  missingFields: [],
  mismatchedFields: ["heartbeatInterval"],
  staleFields: ["report_generator.lastUpdated"],
  lastAuditedAt: daysAgo(2),
  stewardRecommendations: [
    "Minor drift: heartbeat interval changed from 900 to 600 - update blueprint to match",
  ],
};

const pmMemory: MemorySource[] = [
  {
    id: "ms-pm-001",
    agentId: AGENT_IDS.pm,
    name: "Project Board State",
    type: "shared_context",
    path: "/shared/projects/board",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(0),
    freshnessScore: 1.0,
    dependencies: ["project_board"],
  },
  {
    id: "ms-pm-002",
    agentId: AGENT_IDS.pm,
    name: "Team Capacity Data",
    type: "api",
    path: "/api/agents/workload",
    readPermission: true,
    writePermission: false,
    lastRefresh: daysAgo(0),
    freshnessScore: 0.97,
    dependencies: ["workload_tracker"],
  },
];

const pmHealth: CognitiveHealth = {
  agentId: AGENT_IDS.pm,
  alignmentScore: 0.93,
  driftScore: 0.08,
  completenessScore: 0.94,
  toolPolicyCoverage: 1.0,
  delegationCoverage: 0.95,
  lastAssessed: daysAgo(1),
};

// ---------------------------------------------------------------------------
// QA
// ---------------------------------------------------------------------------

const qaProfile: AgentCognitiveProfile = {
  mission:
    "Validate all software releases through comprehensive testing, ensuring quality standards are met before any code reaches production.",
  cognitiveRole: "Quality Guardian",
  specialization: "Testing strategy, test automation, and release validation",
  priorityStack: [
    "Run regression tests on all PR merges",
    "Validate acceptance criteria for completed tasks",
    "Maintain and expand e2e test suite",
    "Report quality metrics to CTO",
  ],
  decisionRules: [
    "Block release if critical test failures exist",
    "Require 80% code coverage for new features",
    "Approve release only after full regression pass",
  ],
  reasoningSequence: [
    "Identify test scope from PR changes",
    "Run automated test suites",
    "Analyze test results",
    "Report findings to CTO",
    "Approve or block release",
  ],
  escalationTriggers: [
    "Test infrastructure failure",
    "Critical regression in existing functionality",
    "Code coverage drops below 70%",
  ],
  antiPatterns: [
    "Approving releases without running full regression",
    "Ignoring flaky tests instead of fixing them",
    "Testing only happy paths",
  ],
  boundaryRules: [
    "Do not fix bugs directly - report and assign to engineer",
    "Do not skip tests for deadline pressure without CTO approval",
    "Always document test failures with reproduction steps",
  ],
  confidencePolicy: "high",
  edgeCaseRules: [
    "If test environment is unstable, pause testing and notify CTO",
    "If new feature has no testable spec, request clarification from PM",
  ],
  capabilityTags: ["Critique", "Execution", "Analysis"],
  healthStatus: "blocked",
  driftStatus: 0.28,
  blueprintVersion: "1.4.0",
  lastSyncAt: daysAgo(8),
  modelTier: "fast",
  toolCount: 7,
};

const qaSkillChains: SkillChain[] = [
  {
    id: "sc-qa-001",
    agentId: AGENT_IDS.qa,
    name: "Release Validation",
    description: "Full validation pipeline before production release",
    isPrimary: true,
    startConditions: ["Release candidate tagged", "Hotfix PR merged"],
    steps: [
      {
        id: "scs-qa-001-1",
        chainId: "sc-qa-001",
        orderIndex: 0,
        type: "tool_call",
        title: "Run unit tests",
        description: "Execute full unit test suite",
        toolRequired: "test_runner",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "All unit tests pass",
        failureCondition: "Any unit test failure",
      },
      {
        id: "scs-qa-001-2",
        chainId: "sc-qa-001",
        orderIndex: 1,
        type: "tool_call",
        title: "Run integration tests",
        description: "Execute integration test suite against staging",
        toolRequired: "integration_test_runner",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "All integration tests pass",
        failureCondition: "Integration test failure",
      },
      {
        id: "scs-qa-001-3",
        chainId: "sc-qa-001",
        orderIndex: 2,
        type: "tool_call",
        title: "Run e2e tests",
        description: "Execute end-to-end browser tests",
        toolRequired: "e2e_test_runner",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "All e2e tests pass",
        failureCondition: "E2e test failure or timeout",
      },
      {
        id: "scs-qa-001-4",
        chainId: "sc-qa-001",
        orderIndex: 3,
        type: "tool_call",
        title: "Check code coverage",
        description: "Verify code coverage meets minimum threshold",
        toolRequired: "coverage_reporter",
        delegateTarget: null,
        escalationTarget: null,
        successCondition: "Coverage >= 80%",
        failureCondition: "Coverage below threshold",
      },
      {
        id: "scs-qa-001-5",
        chainId: "sc-qa-001",
        orderIndex: 4,
        type: "decision",
        title: "Release decision",
        description: "Approve or block the release based on all test results",
        toolRequired: null,
        delegateTarget: null,
        escalationTarget: AGENT_IDS.cto,
        successCondition: "Release approved",
        failureCondition: "Release blocked with detailed failure report",
      },
    ],
    branches: {
      "test-infra-failure": "sc-qa-003",
    },
    completionCriteria: "Release approved or blocked with documentation",
    fallbackBehavior:
      "Escalate to CTO with partial test results and risk assessment",
    version: "1.5.0",
  },
];

const qaToolPolicies: ToolPolicy[] = [
  {
    id: "tp-qa-001",
    agentId: AGENT_IDS.qa,
    toolName: "test_runner",
    permissionLevel: "full",
    usageConditions: ["Unit test execution", "Regression testing"],
    doNotUseConditions: [],
    fallbackBehavior: "Manual test execution via CLI",
    preconditions: ["Code must be built successfully"],
    notes: "Primary testing tool",
    lastUpdated: daysAgo(0),
    successRate: 0.89,
    failureRate: 0.11,
    usageCount: 5672,
  },
  {
    id: "tp-qa-002",
    agentId: AGENT_IDS.qa,
    toolName: "integration_test_runner",
    permissionLevel: "full",
    usageConditions: ["Pre-release validation", "API contract testing"],
    doNotUseConditions: ["Against production environment"],
    fallbackBehavior: "Run subset of critical integration tests manually",
    preconditions: ["Staging environment must be available"],
    notes: "Requires staging env - currently blocked due to env issue",
    lastUpdated: daysAgo(3),
    successRate: 0.82,
    failureRate: 0.18,
    usageCount: 1234,
  },
  {
    id: "tp-qa-003",
    agentId: AGENT_IDS.qa,
    toolName: "e2e_test_runner",
    permissionLevel: "full",
    usageConditions: ["Release validation", "Critical path testing"],
    doNotUseConditions: [],
    fallbackBehavior: "Manual browser testing checklist",
    preconditions: ["Staging environment must be deployed"],
    notes: "",
    lastUpdated: daysAgo(2),
    successRate: 0.78,
    failureRate: 0.22,
    usageCount: 890,
  },
  {
    id: "tp-qa-004",
    agentId: AGENT_IDS.qa,
    toolName: "coverage_reporter",
    permissionLevel: "full",
    usageConditions: ["After test runs", "Coverage trend analysis"],
    doNotUseConditions: [],
    fallbackBehavior: "Check coverage from CI output",
    preconditions: ["Tests must have run first"],
    notes: "",
    lastUpdated: daysAgo(1),
    successRate: 0.95,
    failureRate: 0.05,
    usageCount: 2345,
  },
  {
    id: "tp-qa-005",
    agentId: AGENT_IDS.qa,
    toolName: "bug_reporter",
    permissionLevel: "full",
    usageConditions: ["Test failures", "Regression discoveries"],
    doNotUseConditions: [],
    fallbackBehavior: "Report bugs via agent messenger",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(0),
    successRate: 0.98,
    failureRate: 0.02,
    usageCount: 567,
  },
  {
    id: "tp-qa-006",
    agentId: AGENT_IDS.qa,
    toolName: "code_editor",
    permissionLevel: "restricted",
    usageConditions: ["Writing test code only"],
    doNotUseConditions: ["Modifying application code"],
    fallbackBehavior: "Delegate test writing to engineer",
    preconditions: ["Must be in test directory"],
    notes: "QA can write tests but not modify application code",
    lastUpdated: daysAgo(5),
    successRate: 0.90,
    failureRate: 0.10,
    usageCount: 345,
  },
  {
    id: "tp-qa-007",
    agentId: AGENT_IDS.qa,
    toolName: "performance_profiler",
    permissionLevel: "read_only",
    usageConditions: ["Performance regression investigation"],
    doNotUseConditions: [],
    fallbackBehavior: "Review CI performance logs",
    preconditions: [],
    notes: "",
    lastUpdated: daysAgo(14),
    successRate: 0.85,
    failureRate: 0.15,
    usageCount: 78,
  },
];

const qaDelegationPolicies: DelegationPolicy[] = [
  {
    id: "dp-qa-001",
    agentId: AGENT_IDS.qa,
    taskClass: "bug_fix",
    ownershipMode: "delegates",
    delegateTo: AGENT_IDS.engineer,
    escalateTo: AGENT_IDS.cto,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "QA reports bugs, engineer fixes them",
  },
  {
    id: "dp-qa-002",
    agentId: AGENT_IDS.qa,
    taskClass: "test_infrastructure",
    ownershipMode: "owns",
    delegateTo: null,
    escalateTo: AGENT_IDS.cto,
    approvalRequired: false,
    confidenceThreshold: "medium",
    notes: "QA owns test infrastructure and tooling",
  },
  {
    id: "dp-qa-003",
    agentId: AGENT_IDS.qa,
    taskClass: "release_approval",
    ownershipMode: "owns",
    delegateTo: null,
    escalateTo: AGENT_IDS.cto,
    approvalRequired: false,
    confidenceThreshold: "high",
    notes: "QA has final say on release quality gates",
  },
];

const qaRuntime: RuntimeProfile = {
  id: "rp-qa-001",
  agentId: AGENT_IDS.qa,
  adapter: "claude_local",
  modelName: "claude-haiku-4-5-20251001",
  modelTier: "fast",
  heartbeatMode: "timer",
  heartbeatInterval: 900,
  cronJobs: ["nightly-regression", "coverage-trend-report", "flaky-test-scan"],
  sandboxMode: true,
  accessProfile: "tester",
  environmentStatus: "degraded",
  exporterVersion: "1.1.0",
};

const qaDrift: AuditDriftReport = {
  id: "adr-qa-001",
  agentId: AGENT_IDS.qa,
  blueprintVersion: "1.4.0",
  liveVersion: "1.2.1",
  driftScore: 0.28,
  missingFields: ["edgeCaseRules[1]", "boundaryRules[2]"],
  mismatchedFields: ["healthStatus", "environmentStatus", "exporterVersion"],
  staleFields: [
    "performance_profiler.lastUpdated",
    "code_editor.lastUpdated",
    "integration_test_runner.notes",
  ],
  lastAuditedAt: daysAgo(8),
  stewardRecommendations: [
    "QA agent is blocked - staging environment issue needs resolution",
    "Blueprint is significantly behind (1.2.1 vs 1.4.0) - schedule re-sync",
    "Health status is 'blocked' which differs from blueprint expectation of 'healthy'",
    "Resolve staging environment issue before running next audit",
  ],
};

const qaMemory: MemorySource[] = [
  {
    id: "ms-qa-001",
    agentId: AGENT_IDS.qa,
    name: "Test Results History",
    type: "database",
    path: "test_results",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(0),
    freshnessScore: 0.96,
    dependencies: ["test_runner", "integration_test_runner", "e2e_test_runner"],
  },
  {
    id: "ms-qa-002",
    agentId: AGENT_IDS.qa,
    name: "Coverage Reports",
    type: "file",
    path: "/reports/coverage/",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(1),
    freshnessScore: 0.90,
    dependencies: ["coverage_reporter"],
  },
  {
    id: "ms-qa-003",
    agentId: AGENT_IDS.qa,
    name: "Flaky Test Registry",
    type: "shared_context",
    path: "/shared/qa/flaky-tests",
    readPermission: true,
    writePermission: true,
    lastRefresh: daysAgo(0),
    freshnessScore: 0.94,
    dependencies: [],
  },
];

const qaHealth: CognitiveHealth = {
  agentId: AGENT_IDS.qa,
  alignmentScore: 0.76,
  driftScore: 0.28,
  completenessScore: 0.80,
  toolPolicyCoverage: 0.86,
  delegationCoverage: 0.90,
  lastAssessed: daysAgo(2),
};

// ---------------------------------------------------------------------------
// Assembled agent data
// ---------------------------------------------------------------------------

export const mockAgentCognitiveData: AgentCognitiveData[] = [
  {
    agentId: AGENT_IDS.ceo,
    agentName: "Atlas",
    agentRole: "ceo",
    profile: ceoProfile,
    skillChains: ceoSkillChains,
    toolPolicies: ceoToolPolicies,
    delegationPolicies: ceoDelegationPolicies,
    runtimeProfile: ceoRuntime,
    auditDriftReport: ceoDrift,
    memorySources: ceoMemory,
    cognitiveHealth: ceoHealth,
  },
  {
    agentId: AGENT_IDS.cto,
    agentName: "Forge",
    agentRole: "cto",
    profile: ctoProfile,
    skillChains: ctoSkillChains,
    toolPolicies: ctoToolPolicies,
    delegationPolicies: ctoDelegationPolicies,
    runtimeProfile: ctoRuntime,
    auditDriftReport: ctoDrift,
    memorySources: ctoMemory,
    cognitiveHealth: ctoHealth,
  },
  {
    agentId: AGENT_IDS.engineer,
    agentName: "Bolt",
    agentRole: "engineer",
    profile: engineerProfile,
    skillChains: engineerSkillChains,
    toolPolicies: engineerToolPolicies,
    delegationPolicies: engineerDelegationPolicies,
    runtimeProfile: engineerRuntime,
    auditDriftReport: engineerDrift,
    memorySources: engineerMemory,
    cognitiveHealth: engineerHealth,
  },
  {
    agentId: AGENT_IDS.designer,
    agentName: "Prism",
    agentRole: "designer",
    profile: designerProfile,
    skillChains: designerSkillChains,
    toolPolicies: designerToolPolicies,
    delegationPolicies: designerDelegationPolicies,
    runtimeProfile: designerRuntime,
    auditDriftReport: designerDrift,
    memorySources: designerMemory,
    cognitiveHealth: designerHealth,
  },
  {
    agentId: AGENT_IDS.pm,
    agentName: "Nexus",
    agentRole: "pm",
    profile: pmProfile,
    skillChains: pmSkillChains,
    toolPolicies: pmToolPolicies,
    delegationPolicies: pmDelegationPolicies,
    runtimeProfile: pmRuntime,
    auditDriftReport: pmDrift,
    memorySources: pmMemory,
    cognitiveHealth: pmHealth,
  },
  {
    agentId: AGENT_IDS.qa,
    agentName: "Sentinel",
    agentRole: "qa",
    profile: qaProfile,
    skillChains: qaSkillChains,
    toolPolicies: qaToolPolicies,
    delegationPolicies: qaDelegationPolicies,
    runtimeProfile: qaRuntime,
    auditDriftReport: qaDrift,
    memorySources: qaMemory,
    cognitiveHealth: qaHealth,
  },
];

// ---------------------------------------------------------------------------
// Dashboard-level metrics (aggregated across all agents)
// ---------------------------------------------------------------------------

export const mockDashboardMetrics: DashboardMetrics = {
  cognitiveHealthScore: 0.87,
  driftCount: 3,
  delegationEfficiency: 0.91,
  toolUsageSummary: {
    code_editor: 4900,
    test_runner: 9548,
    agent_messenger: 4312,
    project_board: 2891,
    code_analyzer: 1247,
    design_tool: 1567,
    workload_tracker: 1456,
    git_cli: 2134,
    monitoring_dashboard: 456,
    code_search: 1893,
    bug_reporter: 567,
    coverage_reporter: 2345,
  },
  runtimeWarnings: [
    "QA agent (Sentinel) is blocked - staging environment unavailable",
    "Designer agent (Prism) has significant blueprint drift (0.34)",
    "CTO agent (Forge) blueprint is 2 minor versions behind",
  ],
  stewardRecommendations: [
    "Resolve staging environment issue to unblock QA agent",
    "Schedule cognitive re-sync for Designer and QA agents",
    "Review CTO heartbeat interval change and update blueprint",
    "Consider upgrading PM model tier to standard if routing latency increases",
  ],
};

// ---------------------------------------------------------------------------
// Convenience lookup helpers
// ---------------------------------------------------------------------------

export function getAgentCognitiveData(
  agentId: string,
): AgentCognitiveData | undefined {
  return mockAgentCognitiveData.find((a) => a.agentId === agentId);
}

export function getAgentCognitiveDataByRole(
  role: string,
): AgentCognitiveData | undefined {
  return mockAgentCognitiveData.find((a) => a.agentRole === role);
}

export { AGENT_IDS as MOCK_AGENT_IDS };
